name: Android CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: cd android-studio-project && chmod +x gradlew
    - name: Build apk
      run: cd android-studio-project && ./gradlew build
    - name: Build debug apk
      run: cd android-studio-project && ./gradlew assembleDebug --stacktrace && find . -name '*.apk'
    #- name: Upload debug apk
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: FakeGPS-for-Tesla-Android-debug
    #    path: ./android-studio-project/FakeGPS-for-Tesla-Android/build/outputs/apk/debug/FakeGPS-for-Tesla-Android-debug.apk
    - name: Release debug apk
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./android-studio-project/FakeGPS-for-Tesla-Android/build/outputs/apk/debug/FakeGPS-for-Tesla-Android-*-debug.apk
         
